---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gamefrontend-deployment
  labels:
    app: game-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: game-frontend
  template:
    metadata:
      labels:
        app: game-frontend
    spec:
      containers:
        - name: game-frontend
          image: jackjackzhou/game-frontend
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: game-frontend-servies
spec:
  type: LoadBalancer
  ports:
  - port: 3001
    targetPort: 80
    protocol: TCP
  selector:
    app: game-frontend
